services:
  database:
    container_name: ${APP_NAME}-container-database
    image: postgres:16.0-alpine3.18
    build:
      context: .
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
